### ISSUE TITLE
Feature request: Detect/update existing TLDs

### ISSUE THREAD

**Issue by vicky8882002** [thecravenone/WHMCS_Bulk_add_TLDs#2] opened 2017-07-30 20:10 UTC
i have run two time domain php and all domain created double instead of overriding see image.and price is not getting updating . whmcs 7
![dfewff](https://user-images.githubusercontent.com/15075159/28756707-42cec80e-7591-11e7-8f59-f50223e36b32.png)

**Comment by thecravenone** [comment] 2017-07-31 17:52
Please note that, per the README, this is expected behavior:

>The script does not check whether a domain already exists in the database.
>
>* If you wish to use the script to update a TLD's pricing, you should delete that TLD's pricing from the WHMCS admin interface first.

As I no longer use WHMCS or have a WHMCS license, I am unable to test any changes that may be made to this script. As a result, this script is no longer under active development.

If you wish to add this feature, please feel free to submit a pull request.

**Comment by thecravenone** [comment] 2017-07-31 17:53
This is also a duplicate of #1 .

**Closed as completed by thecravenone** 2017-07-31 17:53 UTC
Labels: enhancement
